name: Awesome Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  awesomeLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Awesome Lint
        run: npx awesome-lint
